// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: artm/core/internals.proto

#ifndef PROTOBUF_artm_2fcore_2finternals_2eproto__INCLUDED
#define PROTOBUF_artm_2fcore_2finternals_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "artm/messages.pb.h"
// @@protoc_insertion_point(includes)

namespace artm {
namespace core {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_artm_2fcore_2finternals_2eproto();
void protobuf_AssignDesc_artm_2fcore_2finternals_2eproto();
void protobuf_ShutdownFile_artm_2fcore_2finternals_2eproto();

class DataLoaderCacheEntry;

// ===================================================================

class DataLoaderCacheEntry : public ::google::protobuf::Message {
 public:
  DataLoaderCacheEntry();
  virtual ~DataLoaderCacheEntry();

  DataLoaderCacheEntry(const DataLoaderCacheEntry& from);

  inline DataLoaderCacheEntry& operator=(const DataLoaderCacheEntry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DataLoaderCacheEntry& default_instance();

  void Swap(DataLoaderCacheEntry* other);

  // implements Message ----------------------------------------------

  DataLoaderCacheEntry* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataLoaderCacheEntry& from);
  void MergeFrom(const DataLoaderCacheEntry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string batch_uuid = 2;
  inline bool has_batch_uuid() const;
  inline void clear_batch_uuid();
  static const int kBatchUuidFieldNumber = 2;
  inline const ::std::string& batch_uuid() const;
  inline void set_batch_uuid(const ::std::string& value);
  inline void set_batch_uuid(const char* value);
  inline void set_batch_uuid(const char* value, size_t size);
  inline ::std::string* mutable_batch_uuid();
  inline ::std::string* release_batch_uuid();
  inline void set_allocated_batch_uuid(::std::string* batch_uuid);

  // repeated int32 item_id = 3;
  inline int item_id_size() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 3;
  inline ::google::protobuf::int32 item_id(int index) const;
  inline void set_item_id(int index, ::google::protobuf::int32 value);
  inline void add_item_id(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      item_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_item_id();

  // repeated .artm.FloatArray theta = 4;
  inline int theta_size() const;
  inline void clear_theta();
  static const int kThetaFieldNumber = 4;
  inline const ::artm::FloatArray& theta(int index) const;
  inline ::artm::FloatArray* mutable_theta(int index);
  inline ::artm::FloatArray* add_theta();
  inline const ::google::protobuf::RepeatedPtrField< ::artm::FloatArray >&
      theta() const;
  inline ::google::protobuf::RepeatedPtrField< ::artm::FloatArray >*
      mutable_theta();

  // repeated string topic_name = 5;
  inline int topic_name_size() const;
  inline void clear_topic_name();
  static const int kTopicNameFieldNumber = 5;
  inline const ::std::string& topic_name(int index) const;
  inline ::std::string* mutable_topic_name(int index);
  inline void set_topic_name(int index, const ::std::string& value);
  inline void set_topic_name(int index, const char* value);
  inline void set_topic_name(int index, const char* value, size_t size);
  inline ::std::string* add_topic_name();
  inline void add_topic_name(const ::std::string& value);
  inline void add_topic_name(const char* value);
  inline void add_topic_name(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& topic_name() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_topic_name();

  // optional string filename = 6;
  inline bool has_filename() const;
  inline void clear_filename();
  static const int kFilenameFieldNumber = 6;
  inline const ::std::string& filename() const;
  inline void set_filename(const ::std::string& value);
  inline void set_filename(const char* value);
  inline void set_filename(const char* value, size_t size);
  inline ::std::string* mutable_filename();
  inline ::std::string* release_filename();
  inline void set_allocated_filename(::std::string* filename);

  // repeated string item_title = 7;
  inline int item_title_size() const;
  inline void clear_item_title();
  static const int kItemTitleFieldNumber = 7;
  inline const ::std::string& item_title(int index) const;
  inline ::std::string* mutable_item_title(int index);
  inline void set_item_title(int index, const ::std::string& value);
  inline void set_item_title(int index, const char* value);
  inline void set_item_title(int index, const char* value, size_t size);
  inline ::std::string* add_item_title();
  inline void add_item_title(const ::std::string& value);
  inline void add_item_title(const char* value);
  inline void add_item_title(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& item_title() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_item_title();

  // repeated .artm.IntArray topic_index = 8;
  inline int topic_index_size() const;
  inline void clear_topic_index();
  static const int kTopicIndexFieldNumber = 8;
  inline const ::artm::IntArray& topic_index(int index) const;
  inline ::artm::IntArray* mutable_topic_index(int index);
  inline ::artm::IntArray* add_topic_index();
  inline const ::google::protobuf::RepeatedPtrField< ::artm::IntArray >&
      topic_index() const;
  inline ::google::protobuf::RepeatedPtrField< ::artm::IntArray >*
      mutable_topic_index();

  // @@protoc_insertion_point(class_scope:artm.core.DataLoaderCacheEntry)
 private:
  inline void set_has_batch_uuid();
  inline void clear_has_batch_uuid();
  inline void set_has_filename();
  inline void clear_has_filename();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* batch_uuid_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > item_id_;
  ::google::protobuf::RepeatedPtrField< ::artm::FloatArray > theta_;
  ::google::protobuf::RepeatedPtrField< ::std::string> topic_name_;
  ::std::string* filename_;
  ::google::protobuf::RepeatedPtrField< ::std::string> item_title_;
  ::google::protobuf::RepeatedPtrField< ::artm::IntArray > topic_index_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_artm_2fcore_2finternals_2eproto();
  friend void protobuf_AssignDesc_artm_2fcore_2finternals_2eproto();
  friend void protobuf_ShutdownFile_artm_2fcore_2finternals_2eproto();

  void InitAsDefaultInstance();
  static DataLoaderCacheEntry* default_instance_;
};
// ===================================================================


// ===================================================================

// DataLoaderCacheEntry

// optional string batch_uuid = 2;
inline bool DataLoaderCacheEntry::has_batch_uuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DataLoaderCacheEntry::set_has_batch_uuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DataLoaderCacheEntry::clear_has_batch_uuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DataLoaderCacheEntry::clear_batch_uuid() {
  if (batch_uuid_ != &::google::protobuf::internal::GetEmptyString()) {
    batch_uuid_->clear();
  }
  clear_has_batch_uuid();
}
inline const ::std::string& DataLoaderCacheEntry::batch_uuid() const {
  return *batch_uuid_;
}
inline void DataLoaderCacheEntry::set_batch_uuid(const ::std::string& value) {
  set_has_batch_uuid();
  if (batch_uuid_ == &::google::protobuf::internal::GetEmptyString()) {
    batch_uuid_ = new ::std::string;
  }
  batch_uuid_->assign(value);
}
inline void DataLoaderCacheEntry::set_batch_uuid(const char* value) {
  set_has_batch_uuid();
  if (batch_uuid_ == &::google::protobuf::internal::GetEmptyString()) {
    batch_uuid_ = new ::std::string;
  }
  batch_uuid_->assign(value);
}
inline void DataLoaderCacheEntry::set_batch_uuid(const char* value, size_t size) {
  set_has_batch_uuid();
  if (batch_uuid_ == &::google::protobuf::internal::GetEmptyString()) {
    batch_uuid_ = new ::std::string;
  }
  batch_uuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DataLoaderCacheEntry::mutable_batch_uuid() {
  set_has_batch_uuid();
  if (batch_uuid_ == &::google::protobuf::internal::GetEmptyString()) {
    batch_uuid_ = new ::std::string;
  }
  return batch_uuid_;
}
inline ::std::string* DataLoaderCacheEntry::release_batch_uuid() {
  clear_has_batch_uuid();
  if (batch_uuid_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = batch_uuid_;
    batch_uuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void DataLoaderCacheEntry::set_allocated_batch_uuid(::std::string* batch_uuid) {
  if (batch_uuid_ != &::google::protobuf::internal::GetEmptyString()) {
    delete batch_uuid_;
  }
  if (batch_uuid) {
    set_has_batch_uuid();
    batch_uuid_ = batch_uuid;
  } else {
    clear_has_batch_uuid();
    batch_uuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}

// repeated int32 item_id = 3;
inline int DataLoaderCacheEntry::item_id_size() const {
  return item_id_.size();
}
inline void DataLoaderCacheEntry::clear_item_id() {
  item_id_.Clear();
}
inline ::google::protobuf::int32 DataLoaderCacheEntry::item_id(int index) const {
  return item_id_.Get(index);
}
inline void DataLoaderCacheEntry::set_item_id(int index, ::google::protobuf::int32 value) {
  item_id_.Set(index, value);
}
inline void DataLoaderCacheEntry::add_item_id(::google::protobuf::int32 value) {
  item_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DataLoaderCacheEntry::item_id() const {
  return item_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DataLoaderCacheEntry::mutable_item_id() {
  return &item_id_;
}

// repeated .artm.FloatArray theta = 4;
inline int DataLoaderCacheEntry::theta_size() const {
  return theta_.size();
}
inline void DataLoaderCacheEntry::clear_theta() {
  theta_.Clear();
}
inline const ::artm::FloatArray& DataLoaderCacheEntry::theta(int index) const {
  return theta_.Get(index);
}
inline ::artm::FloatArray* DataLoaderCacheEntry::mutable_theta(int index) {
  return theta_.Mutable(index);
}
inline ::artm::FloatArray* DataLoaderCacheEntry::add_theta() {
  return theta_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::artm::FloatArray >&
DataLoaderCacheEntry::theta() const {
  return theta_;
}
inline ::google::protobuf::RepeatedPtrField< ::artm::FloatArray >*
DataLoaderCacheEntry::mutable_theta() {
  return &theta_;
}

// repeated string topic_name = 5;
inline int DataLoaderCacheEntry::topic_name_size() const {
  return topic_name_.size();
}
inline void DataLoaderCacheEntry::clear_topic_name() {
  topic_name_.Clear();
}
inline const ::std::string& DataLoaderCacheEntry::topic_name(int index) const {
  return topic_name_.Get(index);
}
inline ::std::string* DataLoaderCacheEntry::mutable_topic_name(int index) {
  return topic_name_.Mutable(index);
}
inline void DataLoaderCacheEntry::set_topic_name(int index, const ::std::string& value) {
  topic_name_.Mutable(index)->assign(value);
}
inline void DataLoaderCacheEntry::set_topic_name(int index, const char* value) {
  topic_name_.Mutable(index)->assign(value);
}
inline void DataLoaderCacheEntry::set_topic_name(int index, const char* value, size_t size) {
  topic_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DataLoaderCacheEntry::add_topic_name() {
  return topic_name_.Add();
}
inline void DataLoaderCacheEntry::add_topic_name(const ::std::string& value) {
  topic_name_.Add()->assign(value);
}
inline void DataLoaderCacheEntry::add_topic_name(const char* value) {
  topic_name_.Add()->assign(value);
}
inline void DataLoaderCacheEntry::add_topic_name(const char* value, size_t size) {
  topic_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
DataLoaderCacheEntry::topic_name() const {
  return topic_name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
DataLoaderCacheEntry::mutable_topic_name() {
  return &topic_name_;
}

// optional string filename = 6;
inline bool DataLoaderCacheEntry::has_filename() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DataLoaderCacheEntry::set_has_filename() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DataLoaderCacheEntry::clear_has_filename() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DataLoaderCacheEntry::clear_filename() {
  if (filename_ != &::google::protobuf::internal::GetEmptyString()) {
    filename_->clear();
  }
  clear_has_filename();
}
inline const ::std::string& DataLoaderCacheEntry::filename() const {
  return *filename_;
}
inline void DataLoaderCacheEntry::set_filename(const ::std::string& value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyString()) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void DataLoaderCacheEntry::set_filename(const char* value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyString()) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void DataLoaderCacheEntry::set_filename(const char* value, size_t size) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyString()) {
    filename_ = new ::std::string;
  }
  filename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DataLoaderCacheEntry::mutable_filename() {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyString()) {
    filename_ = new ::std::string;
  }
  return filename_;
}
inline ::std::string* DataLoaderCacheEntry::release_filename() {
  clear_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = filename_;
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void DataLoaderCacheEntry::set_allocated_filename(::std::string* filename) {
  if (filename_ != &::google::protobuf::internal::GetEmptyString()) {
    delete filename_;
  }
  if (filename) {
    set_has_filename();
    filename_ = filename;
  } else {
    clear_has_filename();
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}

// repeated string item_title = 7;
inline int DataLoaderCacheEntry::item_title_size() const {
  return item_title_.size();
}
inline void DataLoaderCacheEntry::clear_item_title() {
  item_title_.Clear();
}
inline const ::std::string& DataLoaderCacheEntry::item_title(int index) const {
  return item_title_.Get(index);
}
inline ::std::string* DataLoaderCacheEntry::mutable_item_title(int index) {
  return item_title_.Mutable(index);
}
inline void DataLoaderCacheEntry::set_item_title(int index, const ::std::string& value) {
  item_title_.Mutable(index)->assign(value);
}
inline void DataLoaderCacheEntry::set_item_title(int index, const char* value) {
  item_title_.Mutable(index)->assign(value);
}
inline void DataLoaderCacheEntry::set_item_title(int index, const char* value, size_t size) {
  item_title_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DataLoaderCacheEntry::add_item_title() {
  return item_title_.Add();
}
inline void DataLoaderCacheEntry::add_item_title(const ::std::string& value) {
  item_title_.Add()->assign(value);
}
inline void DataLoaderCacheEntry::add_item_title(const char* value) {
  item_title_.Add()->assign(value);
}
inline void DataLoaderCacheEntry::add_item_title(const char* value, size_t size) {
  item_title_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
DataLoaderCacheEntry::item_title() const {
  return item_title_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
DataLoaderCacheEntry::mutable_item_title() {
  return &item_title_;
}

// repeated .artm.IntArray topic_index = 8;
inline int DataLoaderCacheEntry::topic_index_size() const {
  return topic_index_.size();
}
inline void DataLoaderCacheEntry::clear_topic_index() {
  topic_index_.Clear();
}
inline const ::artm::IntArray& DataLoaderCacheEntry::topic_index(int index) const {
  return topic_index_.Get(index);
}
inline ::artm::IntArray* DataLoaderCacheEntry::mutable_topic_index(int index) {
  return topic_index_.Mutable(index);
}
inline ::artm::IntArray* DataLoaderCacheEntry::add_topic_index() {
  return topic_index_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::artm::IntArray >&
DataLoaderCacheEntry::topic_index() const {
  return topic_index_;
}
inline ::google::protobuf::RepeatedPtrField< ::artm::IntArray >*
DataLoaderCacheEntry::mutable_topic_index() {
  return &topic_index_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace artm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_artm_2fcore_2finternals_2eproto__INCLUDED
