"""
Constants values, used in messages
"""

# TODO: generate this file automatically

Stream_Type_Global = 0
Stream_Type_ItemIdModulus = 1
RegularizerType_SmoothSparseTheta = 0
RegularizerType_SmoothSparsePhi = 1
RegularizerType_DecorrelatorPhi = 2
RegularizerType_LabelRegularizationPhi = 4
RegularizerType_SpecifiedSparsePhi = 5
RegularizerType_ImproveCoherencePhi = 6
RegularizerType_SmoothPtdw = 7
RegularizerType_TopicSelectionTheta = 8
TransformConfig_TransformType_Logarithm = 0
TransformConfig_TransformType_Polynomial = 1
TransformConfig_TransformType_Constant = 2
ScoreType_Perplexity = 0
ScoreType_SparsityTheta = 1
ScoreType_SparsityPhi = 2
ScoreType_ItemsProcessed = 3
ScoreType_TopTokens = 4
ScoreType_ThetaSnippet = 5
ScoreType_TopicKernel = 6
ScoreType_TopicMassPhi = 7
ScoreType_ClassPrecision = 8
PerplexityScoreConfig_Type_UnigramDocumentModel = 0
PerplexityScoreConfig_Type_UnigramCollectionModel = 1
CollectionParserConfig_CollectionFormat_BagOfWordsUci = 0
CollectionParserConfig_CollectionFormat_MatrixMarket = 1
CollectionParserConfig_CollectionFormat_VowpalWabbit = 2
CollectionParserConfig_CollectionFormat_Cooccurrence = 3
CollectionParserConfig_BatchNameType_Guid = 0
CollectionParserConfig_BatchNameType_Code = 1
GetTopicModelArgs_RequestType_Pwt = 0
GetTopicModelArgs_RequestType_Nwt = 1
GetTopicModelArgs_RequestType_TopicNames = 2
GetTopicModelArgs_RequestType_Tokens = 3
InitializeModelArgs_SourceType_Dictionary = 0
InitializeModelArgs_SourceType_Batches = 1
SpecifiedSparsePhiConfig_SparseMode_SparseTopics = 0
SpecifiedSparsePhiConfig_SparseMode_SparseTokens = 1
SmoothPtdwConfig_SmoothType_MovingAverage = 1
SmoothPtdwConfig_SmoothType_MovingProduct = 2
ProcessBatchesArgs_ThetaMatrixType_None = 0
ProcessBatchesArgs_ThetaMatrixType_Dense = 1
ProcessBatchesArgs_ThetaMatrixType_Sparse = 2
ProcessBatchesArgs_ThetaMatrixType_Cache = 3
ProcessBatchesArgs_ThetaMatrixType_DensePtdw = 4
ProcessBatchesArgs_ThetaMatrixType_SparsePtdw = 5
CopyRequestResultArgs_RequestType_DefaultRequestType = 0
CopyRequestResultArgs_RequestType_GetThetaSecondPass = 1
CopyRequestResultArgs_RequestType_GetModelSecondPass = 2
GetTopicModelArgs_MatrixLayout_Dense = 0
GetTopicModelArgs_MatrixLayout_Sparse = 1
GetThetaMatrixArgs_MatrixLayout_Dense = 0
GetThetaMatrixArgs_MatrixLayout_Sparse = 1
TransformMasterModelArgs_ThetaMatrixType_None = 0
TransformMasterModelArgs_ThetaMatrixType_Dense = 1
TransformMasterModelArgs_ThetaMatrixType_Sparse = 2
TransformMasterModelArgs_ThetaMatrixType_Cache = 3
TransformMasterModelArgs_ThetaMatrixType_DensePtdw = 4
TransformMasterModelArgs_ThetaMatrixType_SparsePtdw = 5
